const PERIODS = {
    1: { label: "Period 1", dates: "1491–1607", theme: "Contact & Colonization", color: "#7055c0" },
    2: { label: "Period 2", dates: "1607–1754", theme: "Colonization & Settlement", color: "#1d8a68" },
    3: { label: "Period 3", dates: "1754–1800", theme: "Revolution & Republic", color: "#c04a1a" },
    4: { label: "Period 4", dates: "1800–1848", theme: "Democracy & Expansion", color: "#2070c0" },
    5: { label: "Period 5", dates: "1844–1877", theme: "Civil War & Reconstruction", color: "#b83868" },
    6: { label: "Period 6", dates: "1865–1898", theme: "Gilded Age", color: "#4a8a18" },
    7: { label: "Period 7", dates: "1890–1945", theme: "Progressive Era to WWII", color: "#a05818" },
    8: { label: "Period 8", dates: "1945–1980", theme: "Cold War America", color: "#4030a0" },
    9: { label: "Period 9", dates: "1980–Present", theme: "Contemporary America", color: "#2a6828" },
};

const EVENTS = [
    // Period 1
    { year: 1491, title: "Pre-Columbian Americas", p: 1, tag: "society", desc: "Diverse Native civilizations — Aztec, Inca, Mississippian, Pueblo — thrived with complex political, economic, and agricultural systems before European contact.", conn: "Foundation for understanding native–European interaction. APUSH emphasizes the sophistication of these societies before colonization." },
    { year: 1492, title: "Columbus Reaches the Caribbean", p: 1, tag: "expansion", desc: "Columbus's voyage initiated sustained contact between Europe and the Americas, triggering the Columbian Exchange of crops, animals, and diseases.", conn: "Triggers European competition for American territory and centuries of cultural and biological exchange — a core APUSH continuity theme." },
    { year: 1519, title: "Cortés Conquers the Aztec Empire", p: 1, tag: "conflict", desc: "With a small force and indigenous allies, Cortés defeated the Aztecs — demonstrating how disease, diplomacy, and military technology enabled conquest.", conn: "Model for later European conquest patterns. Analyze the roles of disease, alliances, and technology in Spanish success." },
    { year: 1565, title: "St. Augustine Founded", p: 1, tag: "expansion", desc: "Oldest continuously occupied European settlement in North America, founded by Spain as a military outpost in Florida.", conn: "Reflects Spanish imperial strategy. Useful for Period 2 comparisons of colonial motivations and models." },

    // Period 2
    { year: 1607, title: "Jamestown Founded", p: 2, tag: "expansion", desc: "England's first permanent North American settlement, established by the Virginia Company for profit. Early years marked by starvation, disease, and conflict with the Powhatan Confederacy.", conn: "Begins English colonial presence. APUSH uses Jamestown to compare English, Spanish, and French colonial models and labor systems." },
    { year: 1619, title: "First Africans Arrive in Virginia", p: 2, tag: "society", desc: "Arrival of approximately 20 enslaved Africans at Point Comfort began the African presence in English North America, laying groundwork for chattel slavery.", conn: "Critical APUSH origin point for race and slavery as central themes. Connect to Bacon's Rebellion and the hardening of racial slavery laws." },
    { year: 1620, title: "Mayflower Compact", p: 2, tag: "politics", desc: "Pilgrims created a self-governing covenant aboard the Mayflower, reflecting Protestant ideals of community and representative governance.", conn: "Early example of colonial self-government — APUSH traces this tradition through colonial assemblies to the Constitutional Convention." },
    { year: 1676, title: "Bacon's Rebellion", p: 2, tag: "conflict", desc: "Nathaniel Bacon led a multiracial coalition of poor farmers and servants against Virginia's colonial elite, challenging class and racial hierarchy.", conn: "Key APUSH turning point: accelerated the shift from indentured servitude to African chattel slavery as planters sought a more controllable labor force." },
    { year: 1692, title: "Salem Witch Trials", p: 2, tag: "society", desc: "Over 200 accused; 20 executed. Reflected social tensions, gender dynamics, and Puritan religious anxiety in Massachusetts.", conn: "APUSH uses Salem to illustrate social fractures in Puritan New England and the limits of theocratic governance." },

    // Period 3
    { year: 1754, title: "French and Indian War", p: 3, tag: "conflict", desc: "North American theater of the Seven Years' War; expelled France from North America and saddled Britain with enormous debt.", conn: "British war debt led directly to colonial taxation — APUSH traces this to the Stamp Act, Sons of Liberty, and revolution." },
    { year: 1763, title: "Proclamation of 1763", p: 3, tag: "politics", desc: "Britain banned colonial settlement west of the Appalachians to reduce conflict with Native Americans, angering land-hungry colonists.", conn: "First major friction between British authority and colonial expectations — sets the stage for escalating tensions." },
    { year: 1775, title: "Lexington and Concord", p: 3, tag: "conflict", desc: "The 'shot heard round the world' — first military engagements of the Revolutionary War, as colonial Minutemen clashed with British regulars.", conn: "APUSH: marks the transition from political protest to armed revolution. Know the ideological foundations behind colonial resistance." },
    { year: 1776, title: "Declaration of Independence", p: 3, tag: "politics", desc: "Jefferson articulated Enlightenment ideals of natural rights, popular sovereignty, and the social contract as justification for independence from Britain.", conn: "Foundational APUSH document. Know its Enlightenment influences (Locke), its contradictions regarding slavery, and its use by later reform movements." },
    { year: 1781, title: "Battle of Yorktown", p: 3, tag: "conflict", desc: "Cornwallis's surrender ended major Revolutionary War fighting, secured by French naval and military support.", conn: "APUSH emphasizes France's critical role and the limits of British strategy. Effectively ended the Revolutionary War." },
    { year: 1787, title: "Constitutional Convention", p: 3, tag: "politics", desc: "Delegates in Philadelphia replaced the Articles of Confederation with a stronger federal framework — separation of powers, federalism, and checks and balances.", conn: "Core APUSH content. Know the major compromises (3/5, Great, Commerce/Slave Trade) and the Federalist vs. Anti-Federalist debates." },
    { year: 1798, title: "Alien and Sedition Acts", p: 3, tag: "politics", desc: "Federalist legislation targeted immigrants and government critics, provoking the Virginia and Kentucky Resolutions asserting states' rights.", conn: "Early test of free speech and federal vs. state authority — APUSH connects this to nullification debates in the antebellum era." },

    // Period 4
    { year: 1803, title: "Louisiana Purchase", p: 4, tag: "expansion", desc: "Napoleon sold the Louisiana Territory for $15 million, doubling the nation's size and raising constitutional questions about executive power.", conn: "Intensified debates over slavery's expansion into new territories — a tension that escalates through the Compromise of 1850 to the Civil War." },
    { year: 1812, title: "War of 1812", p: 4, tag: "conflict", desc: "War with Britain over impressment and western expansion. Ended inconclusively but sparked a surge of American nationalism and accelerated industrial development.", conn: "APUSH: led to the Era of Good Feelings and a burst of economic nationalism. Know the Hartford Convention as a Federalist miscalculation." },
    { year: 1820, title: "Missouri Compromise", p: 4, tag: "politics", desc: "Admitted Missouri as a slave state and Maine free; drew the 36°30' line to regulate slavery's future expansion westward.", conn: "Key APUSH sectional compromise. LEQs often ask you to compare Missouri, 1850, and Kansas-Nebraska compromises — know the pattern." },
    { year: 1828, title: "Tariff of Abominations", p: 4, tag: "economy", desc: "High protective tariff enraged Southern states, leading to the Nullification Crisis and Calhoun's states' rights doctrine.", conn: "APUSH: prefigures sectional conflict over federal power vs. state sovereignty. Jackson's firm response showed the limits of nullification." },
    { year: 1830, title: "Indian Removal Act", p: 4, tag: "politics", desc: "Authorized forced removal of Native Americans from the Southeast, leading to the Trail of Tears (1838–39) and thousands of deaths.", conn: "Starkest example of racial dispossession in the antebellum era. Note that the Supreme Court ruled against removal, but Jackson defied it." },
    { year: 1831, title: "Nat Turner's Rebellion", p: 4, tag: "conflict", desc: "The largest slave revolt in U.S. history — Turner led ~70 enslaved people in Virginia, killing 55 white residents before being suppressed.", conn: "APUSH turning point: hardened Southern slave codes and suppressed abolitionist mail. Intensified the proslavery ideology of the antebellum South." },
    { year: 1845, title: "Manifest Destiny", p: 4, tag: "expansion", desc: "The ideology that American westward expansion was divinely ordained — used to justify annexation of Texas and war with Mexico.", conn: "Core APUSH concept for Period 4–5. Know how Manifest Destiny intersected with race, Native displacement, and the slavery debate." },
    { year: 1848, title: "Treaty of Guadalupe Hidalgo", p: 4, tag: "expansion", desc: "Ended the Mexican-American War; the U.S. gained California, New Mexico, and other territories — reigniting the slavery expansion debate.", conn: "APUSH: the Mexican Cession directly triggered the Wilmot Proviso debate and the Compromise of 1850. A key cause of the Civil War." },
    { year: 1848, title: "Seneca Falls Convention", p: 4, tag: "society", desc: "First women's rights convention in the U.S., producing the Declaration of Sentiments modeled on the Declaration of Independence.", conn: "Foundation of the women's suffrage movement — APUSH connects it to abolitionism and the reform culture of the Second Great Awakening." },

    // Period 5
    { year: 1850, title: "Compromise of 1850", p: 5, tag: "politics", desc: "Five bills temporarily resolved the slavery crisis: admitted California free, passed a stronger Fugitive Slave Act, and left other territories to popular sovereignty.", conn: "APUSH: inflamed Northern opinion via the Fugitive Slave Act. Compare with Missouri Compromise and Kansas-Nebraska Act on LEQs." },
    { year: 1854, title: "Bleeding Kansas", p: 5, tag: "conflict", desc: "Pro- and anti-slavery settlers flooded Kansas after the Kansas-Nebraska Act opened the territory to popular sovereignty, resulting in violent civil conflict.", conn: "APUSH: demonstrated that legislative compromise had failed. Bleeding Kansas helped birth the Republican Party and radicalized both sections." },
    { year: 1859, title: "Harpers Ferry Raid", p: 5, tag: "conflict", desc: "John Brown seized the federal arsenal at Harpers Ferry, Virginia, hoping to ignite a slave rebellion. He was captured, tried, and hanged.", conn: "APUSH: polarized North and South. Southerners feared Northern aggression; many Northerners viewed Brown as a martyr — made compromise impossible." },
    { year: 1860, title: "Election of Lincoln", p: 5, tag: "politics", desc: "Lincoln won without a single Southern electoral vote. Southern states began seceding before his inauguration, viewing his election as a mortal threat to slavery.", conn: "APUSH: the direct trigger for secession and Civil War. Know the four-way split of the Democratic Party and what Lincoln's election symbolized." },
    { year: 1861, title: "First & Second Bull Run", p: 5, tag: "conflict", desc: "Two Confederate victories near Manassas, Virginia shattered Northern hopes for a quick war and demonstrated the Confederacy's military strength.", conn: "APUSH: ended Northern illusions of a short war. First Bull Run shocked Washington; Second Bull Run preceded Lee's invasion of the North." },
    { year: 1861, title: "Civil War Begins", p: 5, tag: "conflict", desc: "Confederate attack on Fort Sumter launched four years of war. Over 620,000 soldiers died in a conflict over union, slavery, and the nature of American democracy.", conn: "Know the causes (slavery, sectionalism, election of 1860), major turning points (Antietam, Gettysburg), and the war's social impact." },
    { year: 1862, title: "Battle of Antietam", p: 5, tag: "conflict", desc: "Bloodiest single day in American military history — ~23,000 casualties. Lee's invasion of Maryland was repelled, giving Lincoln the battlefield victory he needed.", conn: "APUSH: enabled Lincoln to issue the Emancipation Proclamation from a position of strength. Prevented British recognition of the Confederacy." },
    { year: 1863, title: "Emancipation Proclamation", p: 5, tag: "politics", desc: "Lincoln declared enslaved people in Confederate states free, reframing the war as a fight against slavery and enabling Black men to enlist.", conn: "APUSH moral turning point. Note its limits (only Confederate states), military strategy implications, and path to the 13th Amendment." },
    { year: 1863, title: "Battle of Gettysburg", p: 5, tag: "conflict", desc: "Three-day battle in Pennsylvania — the Confederacy's farthest northern advance. Lee's defeat ended any realistic hope of European intervention or a negotiated peace.", conn: "APUSH: the war's decisive turning point. Pair with the Gettysburg Address on APUSH essays about Union war aims and national identity." },
    { year: 1865, title: "Appomattox / War Ends", p: 5, tag: "conflict", desc: "Lee surrendered to Grant at Appomattox Court House on April 9, 1865, effectively ending the Civil War. The 13th Amendment abolished slavery that December.", conn: "Know what came next: competing visions of Reconstruction (Lincoln, Radical Republicans, Johnson) and why it ultimately failed." },
    { year: 1865, title: "13th Amendment", p: 5, tag: "politics", desc: "Formally abolished slavery and involuntary servitude throughout the United States — the most significant constitutional change since the Bill of Rights.", conn: "APUSH: always pair with the 14th and 15th Amendments as the Reconstruction Amendments that transformed American citizenship." },
    { year: 1877, title: "Compromise of 1877", p: 5, tag: "politics", desc: "Ended the disputed 1876 election by awarding the presidency to Hayes; in exchange, federal troops withdrew from the South, ending Reconstruction.", conn: "APUSH: marked the abandonment of Black civil rights in the South. Reconstruction's collapse enabled Jim Crow for the next 90 years." },

    // Period 6
    { year: 1869, title: "Transcontinental Railroad", p: 6, tag: "economy", desc: "Joined the nation coast-to-coast, accelerating western settlement, industrial growth, and the displacement of Native peoples from the Great Plains.", conn: "APUSH symbol of industrial capitalism's power and the federal government's role in economic development via land grants." },
    { year: 1870, title: "Bessemer Process", p: 6, tag: "economy", desc: "The Bessemer converter enabled mass production of cheap, high-quality steel — the backbone of railroads, skyscrapers, and industrial infrastructure.", conn: "APUSH: technological foundation of the Gilded Age industrial boom. Connect to Carnegie's rise and the Gospel of Wealth ideology." },
    { year: 1880, title: "Knights of Labor / AFL", p: 6, tag: "economy", desc: "The Knights of Labor organized workers across craft lines including women and Black workers; the AFL under Gompers took a narrower, craft-union approach.", conn: "APUSH: know the contrast between the Knights' inclusive industrial unionism and the AFL's 'bread and butter' exclusionary strategy." },
    { year: 1882, title: "Chinese Exclusion Act", p: 6, tag: "politics", desc: "First federal law restricting immigration by nationality, reflecting nativist anxieties about race and labor competition on the West Coast.", conn: "APUSH precedent for immigration restriction — connects to the Immigration Acts of 1917 and 1924 and broader debates about American identity." },
    { year: 1889, title: "Gospel of Wealth", p: 6, tag: "society", desc: "Andrew Carnegie's essay argued that the wealthy had a duty to use their fortunes for the public good — the ideological justification for Gilded Age philanthropy.", conn: "APUSH: contrast with Social Darwinism and Henry George's single-tax movement. Used to analyze Gilded Age attitudes toward wealth and poverty." },
    { year: 1896, title: "Plessy v. Ferguson", p: 6, tag: "politics", desc: "Supreme Court upheld 'separate but equal' doctrine, giving constitutional backing to Jim Crow segregation across the South.", conn: "Key APUSH case enshrining segregation for 58 years. Always pair with Brown v. Board (1954) on change-over-time essays about civil rights." },

    // Period 7
    { year: 1898, title: "U.S. Imperialism (Hawaii/Philippines)", p: 7, tag: "expansion", desc: "Hawaii was annexed; the Philippines, Guam, and Puerto Rico acquired from Spain after the Spanish-American War — marking America's emergence as a Pacific empire.", conn: "APUSH: opens debates about imperialism, race, and American identity. Know the Anti-Imperialist League's arguments and debates over empire." },
    { year: 1913, title: "16th & 17th Amendments", p: 7, tag: "politics", desc: "Income tax and direct election of senators — landmark Progressive Era reforms shifting power away from corporate interests and state legislatures.", conn: "APUSH: structural Progressive changes. Know the full reform agenda: 16th, 17th, 18th, 19th Amendments and the new regulatory agencies." },
    { year: 1917, title: "U.S. Enters World War I", p: 7, tag: "conflict", desc: "Wilson entered the war framing it as a fight for democracy; at home, the Espionage and Sedition Acts suppressed dissent against the war.", conn: "APUSH: reshaped the global order and disillusioned Americans. The Senate's rejection of the League of Nations connects to 1920s isolationism." },
    { year: 1919, title: "Prohibition Begins (18th Amend.)", p: 7, tag: "society", desc: "The 18th Amendment banned alcohol production and sale nationwide — a triumph of the temperance movement, driven largely by Progressive-era reformers.", conn: "APUSH: illustrates Progressive-era moral reform. Prohibition's failure (repealed 1933) showed limits of legislating morality." },
    { year: 1920, title: "19th Amendment", p: 7, tag: "politics", desc: "Granted women the right to vote after decades of suffragist activism — the largest single expansion of the American electorate.", conn: "APUSH culmination of the suffrage movement. Note internal tensions around race and the movement's connections to the Progressive Era." },
    { year: 1929, title: "Great Depression Begins", p: 7, tag: "economy", desc: "Stock market crash triggered mass unemployment, bank failures, and economic devastation — 25% unemployment by 1933.", conn: "APUSH: transformed the citizen–government relationship. The Depression made the New Deal politically necessary and permanently reshaped federalism." },
    { year: 1933, title: "Prohibition Repealed (21st Amend.)", p: 7, tag: "society", desc: "The 21st Amendment repealed Prohibition after 13 years — acknowledging that enforcement had failed and fueled organized crime.", conn: "APUSH: only constitutional amendment to repeal another. Demonstrates limits of reform through legal prohibition." },
    { year: 1941, title: "Pearl Harbor / U.S. Enters WWII", p: 7, tag: "conflict", desc: "Japan's attack brought the U.S. into WWII, mobilizing the entire economy and society. Also led to internment of 120,000 Japanese Americans under Executive Order 9066.", conn: "APUSH: WWII ended the Depression, established American global hegemony, and set the stage for the Cold War. Know the home front impacts." },
    { year: 1945, title: "End of Pacific Theater (WWII)", p: 7, tag: "conflict", desc: "Atomic bombs dropped on Hiroshima and Nagasaki; Japan surrendered August 15, 1945 — ending WWII and beginning the nuclear age.", conn: "APUSH: raises debates about the atomic bomb's justification. Marks the U.S. emergence as the world's dominant military and economic power." },

    // Period 8
    { year: 1947, title: "Truman Doctrine & Marshall Plan", p: 8, tag: "politics", desc: "U.S. committed to containing communism globally (Truman Doctrine) and rebuilding Western Europe economically (Marshall Plan) — defining Cold War strategy.", conn: "APUSH: established the containment policy that guided U.S. foreign policy for 40 years. Know NSC-68 as the key document expanding this commitment." },
    { year: 1948, title: "Berlin Airlift", p: 8, tag: "conflict", desc: "For 11 months, the U.S. and allies airlifted supplies into West Berlin after the Soviet Union blockaded all land routes — a major Cold War standoff.", conn: "APUSH: demonstrated American resolve to resist Soviet pressure without direct military confrontation — the essence of containment in action." },
    { year: 1949, title: "NATO Formed", p: 8, tag: "politics", desc: "The North Atlantic Treaty Organization created a mutual defense alliance among Western democracies, committing the U.S. to collective European security.", conn: "APUSH: first peacetime entangling alliance in American history — a break from Washington's Farewell Address tradition. Know its Cold War significance." },
    { year: 1949, title: "USSR Gets Nuclear Weapons", p: 8, tag: "conflict", desc: "The Soviet Union successfully tested its first atomic bomb, ending the American nuclear monopoly and dramatically escalating Cold War tension.", conn: "APUSH: triggered NSC-68 and the H-bomb decision. Accelerated the arms race and deepened American anxiety about communist infiltration (McCarthyism)." },
    { year: 1950, title: "Korean War", p: 8, tag: "conflict", desc: "North Korea invaded South Korea; the U.S. led a UN coalition to defend the South. Ended in armistice (1953) along the original 38th parallel.", conn: "APUSH: first major 'hot war' of the Cold War. Know Truman's firing of MacArthur as a landmark assertion of civilian control over the military." },
    { year: 1954, title: "Brown v. Board of Education", p: 8, tag: "politics", desc: "Supreme Court unanimously overturned Plessy v. Ferguson, ruling school segregation unconstitutional — energizing the civil rights movement.", conn: "APUSH landmark — always pair with Plessy on change-over-time essays. Know Chief Justice Warren's unanimous opinion and its Cold War context." },
    { year: 1960, title: "Rise of Black Militancy", p: 8, tag: "society", desc: "SNCC, Black Power, and figures like Malcolm X and Stokely Carmichael pushed beyond integration toward Black self-determination, separatism, and economic justice.", conn: "APUSH: marks a generational and ideological shift within the civil rights movement. Know the contrast with MLK's nonviolent approach and SCLC." },
    { year: 1964, title: "Civil Rights Act & Gulf of Tonkin", p: 8, tag: "politics", desc: "The Civil Rights Act banned discrimination; the Gulf of Tonkin Resolution authorized Vietnam escalation — two pivotal events that defined LBJ's presidency.", conn: "APUSH: together defined the Great Society and its undoing as Vietnam consumed political capital and triggered the credibility gap." },
    { year: 1965, title: "Vietnam War Escalation", p: 8, tag: "conflict", desc: "Operation Rolling Thunder bombing campaign and deployment of 184,000 ground troops dramatically escalated U.S. involvement in Vietnam.", conn: "APUSH: know the domino theory rationale, escalation decisions, the Tet Offensive (1968), and the anti-war movement's political impact." },
    { year: 1969, title: "Gay Rights Movement (Stonewall)", p: 8, tag: "society", desc: "The Stonewall Inn riots in New York City — sparked by a police raid on a gay bar — launched the modern gay rights movement and annual Pride marches.", conn: "APUSH: part of the broader 1960s–70s rights revolution. Connect to second-wave feminism, the counterculture, and identity politics." },
    { year: 1972, title: "Watergate", p: 8, tag: "politics", desc: "Nixon's cover-up of the Watergate break-in led to his resignation in 1974 — the only presidential resignation in U.S. history.", conn: "APUSH: shattered public trust in government. Fueled anti-government sentiment that helped elect Reagan in 1980 and shaped modern political cynicism." },

    // Period 9
    { year: 1980, title: "Reagan Revolution", p: 9, tag: "politics", desc: "Reagan's election signaled a conservative realignment — tax cuts, deregulation, anti-communism, and 'Morning in America' optimism replaced the New Deal liberal consensus.", conn: "APUSH: know Reaganomics (supply-side/trickle-down), the Religious Right's rise, and how Reagan's coalition reshaped both parties." },
    { year: 1989, title: "Cold War Ends", p: 9, tag: "politics", desc: "Fall of the Berlin Wall (1989) and dissolution of the Soviet Union (1991) ended the defining conflict of the postwar era.", conn: "APUSH: left the U.S. as the world's sole superpower — raises new questions about the purpose of American foreign policy that persist today." },
    { year: 1994, title: "NAFTA", p: 9, tag: "economy", desc: "North American Free Trade Agreement created a free-trade zone with Canada and Mexico, accelerating economic integration but contributing to manufacturing job losses.", conn: "APUSH: Clinton-era embrace of globalization — fueled debates about trade, deindustrialization, and economic inequality that persist into the 21st century." },
    { year: 2001, title: "September 11 / Afghanistan War", p: 9, tag: "conflict", desc: "Al-Qaeda's attacks killed nearly 3,000; the U.S. invaded Afghanistan and later Iraq, reshaping foreign policy, civil liberties, and national security.", conn: "APUSH: know the PATRIOT Act, debates over civil liberties vs. security, Iraq War justifications, and the long-term cost of the 'War on Terror.'" },
    { year: 2008, title: "Financial Crisis & Obama Election", p: 9, tag: "economy", desc: "Worst economic crisis since the Depression coincided with the historic election of the first African American president.", conn: "APUSH: led to the Affordable Care Act and the Tea Party backlash — illustrates how economic crisis drives political realignment." },
];